ci:
  collect:
    additive: true
    staticDistDir: ./dist
    numberOfRuns: 3
  upload:
    target: temporary-public-storage
  assert:
    aggregation: median-run
    preset: lighthouse:recommended
