---
name: Lint & Fix Codebase

on: # yamllint disable-line rule:truthy
  push: null
  workflow_dispatch:

permissions:
  contents: read

jobs:
  fix-lint:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - name: Super-Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ESLINT_USE_FLAT_CONFIG: false
          VALIDATE_JAVASCRIPT_PRETTIER: false
          VALIDATE_CSS_PRETTIER: false
          VALIDATE_CSS: false
          VALIDATE_HTML_PRETTIER: false
          VALIDATE_JSON_PRETTIER: false
          VALIDATE_JSX_PRETTIER: false
          VALIDATE_MARKDOWN_PRETTIER: false
          VALIDATE_TYPESCRIPT_PRETTIER: false
          VALIDATE_YAML_PRETTIER: false
          FIX_JAVASCRIPT_ES: true
          FIX_JAVASCRIPT_STANDARD: true
          FIX_JSON: true
          FIX_JSX: true
          FIX_MARKDOWN: true
      - name: Commit and push linting fixes
        if: >
          github.event_name == 'pull_request' &&
          github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: ${{ github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: lint[bot]
          commit_user_email: lint[bot]@users.noreply.github.com
          commit_author: lint[bot] <lint[bot]@users.noreply.github.com>
