name: Lighthouse CI

on:
  workflow_dispatch:
  
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        uses: actions/wait@v2 
        with: 
          seconds: 60
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://gogglesinc.github.io/
            https://gogglesinc.github.io/about
            https://gogglesinc.github.io/blog
            https://gogglesinc.github.io/pricing
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
