name: Lighthouse CI

on: 
  push: 
    branches: ["main"]
  workflow_dispatch:
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://gogglesinc.github.io/
            https://gogglesinc.github.io/about
            https://gogglesinc.github.io/blog
            https://gogglesinc.github.io/pricing
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
