---
name: Lighthouse CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions: read-all

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies & Lighthouse CI
        run: npm ci
      - name: Build
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: "./dist"
  desktop:
    runs-on: ubuntu-latest
    needs: [set-up]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./dist
      - run: npm install -g @lhci/cli@0.14.x
      - name: Run Audits on desktop
        run: lhci autorun --config="./lhci_desktop.json"
  mobile:
    runs-on: ubuntu-latest
    needs: [set-up]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-files
          path: ./dist
      - run: npm install -g @lhci/cli@0.14.x
      - name: Run Audits on mobile
        run: lhci autorun --config="./lhci_mobile.json"
