name: Lighthouse CI

on:
  workflow_dispatch:
  
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Wait
        run: sleep 1m
        shell: bash
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Audit
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://gogglesinc.github.io/
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3
