---
name: Lint & Fix Codebase

on: # yamllint disable-line rule:truthy
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fix-lint:
    permissions:
      contents: write
      statuses: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - run: npm ci
      - name: Super-Linter
        uses: super-linter/super-linter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ESLINT_USE_FLAT_CONFIG: false
          VALIDATE_CSS: false
          FIX_JAVASCRIPT_PRETTIER: true
          FIX_JAVASCRIPT_ES: true
          FIX_JAVASCRIPT_STANDARD: true
          FIX_JSON: true
          FIX_JSX: true
          FIX_MARKDOWN: true
          FIX_YAML_PRETTIER: true
      - name: Commit and push linting fixes
        id: pushfix
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT_PULL_REQUEST }}
          branch: chore/linting-fixes
          commit-message: "chore: fix linting issues"
          title: "chore: fix linting issues"
          committer: lint[bot] <lint[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      - name: Outputs
        if: ${{ steps.pushfix.outputs.pull-request-number }}
        run: |
          echo "Pull Request Number - ${{ steps.pushfix.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pushfix.outputs.pull-request-url }}"
          echo "Pull Request Branch - ${{ steps.pushfix.outputs.pull-request-branch }}"
