---
name: Lint Codebase

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  statuses: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v7
        env:
          ESLINT_USE_FLAT_CONFIG: false
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
