---
name: Unlighthouse CI

on: #yamllint disable-line rule:truthy
  workflow_dispatch:

jobs:
  unlighthouse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Install dependencies & Unlighthouse CI
        run: |
          npm ci
          npm i @unlighthouse/cli puppeteer
      - name: Build & Serve
        run: npm run build && npm run preview
      - name: Run Unlighthouse CI
        run: npm run unlighthouse
      - name: Upload artifact
        id: unlighthouse
        uses: actions/upload-artifact@v4
        with:
          name: unlighthouse-report
          path: ./.lighthouse
      - name: Outputs
        run: |
          echo "Artifact URL - ${{ steps.unlighthouse.outputs.artifact-url }}"
